apiVersion: v1
kind: ServiceAccount
metadata:
  name: superagent
  labels:
    app: superagent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: superagent
  labels:
    app: superagent
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: superagent
  labels:
    app: superagent
subjects:
  - kind: ServiceAccount
    name: superagent
roleRef:
  kind: Role
  name: superagent
  apiGroup: rbac.authorization.k8s.io
